package com.uwika.bean;
// Generated Nov 3, 2013 3:59:07 AM by Hibernate Tools 3.2.1.GA



/**
 * KuliahId generated by hbm2java
 */
public class KuliahId  implements java.io.Serializable {


     private int id;
     private String namamatakuliah;
     private String nik;
     private String nim;

    public KuliahId() {
    }

    public KuliahId(int id, String namamatakuliah, String nik, String nim) {
       this.id = id;
       this.namamatakuliah = namamatakuliah;
       this.nik = nik;
       this.nim = nim;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNamamatakuliah() {
        return this.namamatakuliah;
    }
    
    public void setNamamatakuliah(String namamatakuliah) {
        this.namamatakuliah = namamatakuliah;
    }
    public String getNik() {
        return this.nik;
    }
    
    public void setNik(String nik) {
        this.nik = nik;
    }
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KuliahId) ) return false;
		 KuliahId castOther = ( KuliahId ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getNamamatakuliah()==castOther.getNamamatakuliah()) || ( this.getNamamatakuliah()!=null && castOther.getNamamatakuliah()!=null && this.getNamamatakuliah().equals(castOther.getNamamatakuliah()) ) )
 && ( (this.getNik()==castOther.getNik()) || ( this.getNik()!=null && castOther.getNik()!=null && this.getNik().equals(castOther.getNik()) ) )
 && ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getNamamatakuliah() == null ? 0 : this.getNamamatakuliah().hashCode() );
         result = 37 * result + ( getNik() == null ? 0 : this.getNik().hashCode() );
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         return result;
   }   


}


