package com.uwika.bean;
// Generated Nov 3, 2013 3:59:07 AM by Hibernate Tools 3.2.1.GA



/**
 * Kuliah generated by hbm2java
 */
public class Kuliah implements java.io.Serializable {


    private KuliahId id;

    public Kuliah() {
    }
    
    public Kuliah(KuliahId id) {
       this.id = id;
    }
   
    public KuliahId getId() {
        return this.id;
    }
    
    public void setId(KuliahId id) {
        this.id = id;
    }




}


